import assert from 'node:assert/strict';
import { chromium, expect } from '@playwright/test';
import { spawn } from 'node:child_process';
import { mkdir, readFile } from 'node:fs/promises';
import { readDataDisk, decodeAsciiRecords } from '../packages/cpc-disk/src/data-disk.ts';

const server = spawn(process.execPath, ['node_modules/vite/bin/vite.js', 'preview', '--config', 'apps/desktop/vite.config.ts', '--host', '127.0.0.1', '--port', '5173', '--strictPort'], { stdio: ['ignore', 'pipe', 'pipe'] });
let browser;
let page;
const errors = [];
try {
  await new Promise((resolve, reject) => {
    const timeout = setTimeout(() => reject(new Error('Preview server timeout')), 15000);
    server.stdout.on('data', chunk => { if (String(chunk).includes('127.0.0.1')) { clearTimeout(timeout); resolve(); } });
    server.once('exit', code => { clearTimeout(timeout); reject(new Error(`Preview exited ${code}`)); });
  });
  browser = await chromium.launch({ headless: true });
  page = await browser.newPage({ viewport: { width: 1440, height: 960 } });
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await page.goto('http://127.0.0.1:5173');
  await page.getByRole('heading', { name: 'CPCéleste', exact: true }).waitFor();
  await expect(page.getByRole('button', { name: 'Enregistrer tout', exact: true })).toBeDisabled();
  await expect(page).toHaveTitle('CPCéleste — Atelier Amstrad CPC');
  await expect.poll(() => page.locator('.brand-mark').evaluate(image => image.complete && image.naturalWidth > 0)).toBe(true);
  await page.locator('.monaco-editor .view-line').first().waitFor();
  await page.keyboard.press('Control+Shift+P');
  const palette = page.getByRole('dialog', { name: 'Commandes CPCéleste', exact: true });
  await palette.getByRole('textbox').fill('minimap'); await palette.getByRole('textbox').press('Enter');
  await expect(page.locator('.monaco-editor .minimap')).toBeVisible();
  await page.keyboard.press('Control+p');
  await expect(page.getByRole('dialog', { name: 'Ouvrir rapidement une source', exact: true })).toContainText('MAIN.bas');
  await page.keyboard.press('Escape');
  await page.getByRole('tab', { name: 'MAIN.bas', exact: true }).click({ button: 'right' });
  await expect(page.getByRole('dialog', { name: 'Actions de MAIN.bas', exact: true })).toBeVisible();
  await page.keyboard.press('Escape');
  await page.locator('.monaco-editor .view-line').first().click({ button: 'right' });
  await expect(page.getByText('Renuméroter le BASIC…', { exact: true })).toBeVisible();
  await page.keyboard.press('Escape');
  await page.waitForFunction(() => document.querySelectorAll('.monaco-editor .view-lines span[class*="mtk"]').length > 10);
  const input = page.locator('.monaco-editor textarea');
  await input.focus(); await page.keyboard.press('Control+Home'); await page.keyboard.press('Control+a');
  await page.keyboard.insertText('10 PRI');
  await page.keyboard.press('Control+Space');
  await page.locator('.suggest-widget.visible').waitFor();
  await page.keyboard.press('Enter');
  await page.keyboard.insertText(' "OK"\n20 END\n');
  await page.getByText('Aucun problème détecté dans le sous-ensemble analysé.').waitFor();
  await page.getByRole('button', { name: 'PRINT', exact: true }).click();
  await page.getByRole('heading', { name: 'PRINT', exact: true }).waitFor();
  const diskEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Exporter DSK', exact: true }).click();
  const disk = new Uint8Array(await readFile(await (await diskEvent).path()));
  const files = readDataDisk(disk);
  assert.equal(files[0].name, 'MAIN.BAS');
  assert.equal(new TextDecoder().decode(decodeAsciiRecords(files[0].records)), '10 PRINT "OK"\r\n20 END\r\n\x1a');
  await input.focus(); await page.keyboard.press('Control+a'); await page.keyboard.insertText('10 GOTO 999\n20 END');
  await page.getByRole('button', { name: /La ligne BASIC 999 n’existe/ }).waitFor();
  await page.getByRole('button', { name: 'Exporter DSK', exact: true }).click();
  await page.getByRole('status').filter({ hasText: /999 n’existe/ }).waitFor();
  await input.focus(); await page.keyboard.press('Control+a'); await page.keyboard.insertText('10 GOTO 100\n100 END');
  await page.keyboard.press('Control+Home'); await page.keyboard.press('End'); await page.keyboard.press('F12');
  await page.getByRole('status').filter({ hasText: /L2 · C/ }).waitFor();
  await page.keyboard.press('End'); await page.keyboard.insertText(':REM TARGET');
  const savedEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: /^Enregistrer Ctrl/ }).click();
  const saved = await readFile(await (await savedEvent).path(), 'utf8');
  assert.equal(saved, '10 GOTO 100\n100 END:REM TARGET', 'F12 navigated to BASIC target');
  // Dirty replacement must not silently discard edits.
  await input.focus(); await page.keyboard.press('End'); await page.keyboard.insertText(' X');
  const cancelled = page.waitForEvent('dialog').then(dialog => dialog.dismiss());
  await page.getByRole('button', { name: 'Ouvrir', exact: true }).click();
  await cancelled;
  assert.ok(await page.locator('.tab').textContent().then(text => text.includes('modifié')));
  await page.getByRole('button', { name: 'Renuméroter', exact: true }).click();
  const renumber = page.getByRole('region', { name: 'Renumérotation BASIC' });
  await renumber.getByLabel('Premier nouveau numéro', { exact: true }).fill('1000');
  await renumber.getByRole('button', { name: 'Prévisualiser la renumérotation', exact: true }).click();
  await expectText(renumber, '3 substitutions.');
  await renumber.getByRole('button', { name: 'Appliquer la renumérotation', exact: true }).click();
  await expect(page.locator('.monaco-editor .view-lines')).toContainText('1000 GOTO 1010');
  const renumberDiskEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Exporter DSK', exact: true }).click();
  const renumberDisk = new Uint8Array(await readFile(await (await renumberDiskEvent).path()));
  assert.equal(new TextDecoder().decode(decodeAsciiRecords(readDataDisk(renumberDisk)[0].records)), '1000 GOTO 1010\r\n1010 END:REM TARGET X\r\n\x1a');
  await mkdir('out', { recursive: true }); await page.screenshot({ path: 'out/renumber-alpha.png', fullPage: true });
  await input.focus(); await page.keyboard.press('Control+z');
  await expect(page.locator('.monaco-editor .view-lines')).toContainText('10 GOTO 100');
  await page.keyboard.press('Control+Shift+z');
  await expect(page.locator('.monaco-editor .view-lines')).toContainText('1000 GOTO 1010');
  await page.keyboard.press('Control+z');
  await renumber.getByRole('button', { name: 'Prévisualiser la renumérotation', exact: true }).click();
  await input.focus(); await page.keyboard.press('Control+End'); await page.keyboard.insertText(' Y'); await page.keyboard.press('Control+z');
  await renumber.getByRole('button', { name: 'Appliquer la renumérotation', exact: true }).click();
  await expectText(renumber, 'révision modifié depuis l’aperçu');
  await page.keyboard.press('Control+Shift+f');
  const search = page.getByRole('region', { name: 'Recherche dans les sources', exact: true });
  await search.getByLabel('Texte à rechercher', { exact: true }).fill('TARGET');
  await search.getByRole('button', { name: 'Rechercher toutes les sources', exact: true }).click();
  await expect(search).toContainText('1 occurrence(s).');
  await search.getByRole('button', { name: /MAIN.bas · L2:/ }).click();
  await search.getByLabel('Texte de remplacement', { exact: true }).fill('REPLACED');
  await search.getByRole('button', { name: 'Prévisualiser les remplacements', exact: true }).click();
  await search.getByRole('button', { name: 'Appliquer les remplacements sélectionnés', exact: true }).click();
  await expect(page.locator('.monaco-editor .view-lines')).toContainText('REPLACED');
  await input.focus(); await page.keyboard.press('Control+z');
  await expect(page.locator('.monaco-editor .view-lines')).toContainText('TARGET');
  await page.keyboard.press('Control+Shift+z');
  await expect(page.locator('.monaco-editor .view-lines')).toContainText('REPLACED');
  await search.getByRole('button', { name: 'Rechercher toutes les sources', exact: true }).click();
  await input.focus(); await page.keyboard.press('Control+End'); await page.keyboard.insertText(' STALE');
  await expect(search).toContainText('Sources modifiées depuis la recherche');
  await expect(search.getByRole('button', { name: 'Prévisualiser les remplacements', exact: true })).toBeDisabled();
  await mkdir('out', { recursive: true });
  await page.screenshot({ path: 'out/editor-alpha.png', fullPage: true });
  assert.deepEqual(errors, [], 'No browser errors');
  console.log('Editor browser smoke: completion, coloration, help, diagnostics, F12, downloads, dirty protection plus renumber preview/apply/DSK/undo/redo/stale revision passed.');
} catch (error) {
  await mkdir('out', { recursive: true });
  await page?.screenshot({ path: 'out/editor-failure.png', fullPage: true, timeout: 5000 }).catch(() => undefined);
  console.error('Browser errors:', errors);
  console.error(await page?.locator('.view-lines').textContent());
  throw error;
} finally { await browser?.close(); server.kill(); }

async function expectText(locator, text) {
  await locator.getByText(text, { exact: false }).waitFor();
}
