import assert from 'node:assert/strict';
import { verifyPanelLayout } from './panel-layout-smoke.mjs';
import { chromium, expect } from '@playwright/test';
import { spawn } from 'node:child_process';
import { mkdir, readFile } from 'node:fs/promises';
import { readDataDisk, decodeAsciiRecords } from '../packages/cpc-disk/src/data-disk.ts';

const server = spawn(process.execPath, ['node_modules/vite/bin/vite.js', 'preview', '--config', 'apps/desktop/vite.config.ts', '--host', '127.0.0.1', '--port', '5173', '--strictPort'], { stdio: ['ignore', 'pipe', 'pipe'] });
let browser;
let page;
const errors = [];
try {
  await new Promise((resolve, reject) => {
    const timeout = setTimeout(() => reject(new Error('Preview server timeout')), 15000);
    server.stdout.on('data', chunk => { if (String(chunk).includes('127.0.0.1')) { clearTimeout(timeout); resolve(); } });
    server.once('exit', code => { clearTimeout(timeout); reject(new Error(`Preview exited ${code}`)); });
  });
  browser = await chromium.launch({ headless: true });
  const editorContext = await browser.newContext({ viewport: { width: 1440, height: 960 } });
  page = await editorContext.newPage();
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await page.goto('http://127.0.0.1:5173');
  await page.getByRole('heading', { name: 'CPCéleste', exact: true }).waitFor();
  await expect(page.getByRole('button', { name: 'Enregistrer tout', exact: true })).toBeDisabled();
  await expect(page).toHaveTitle('CPCéleste — Atelier Amstrad CPC');
  await expect.poll(() => page.locator('.brand-mark').evaluate(image => image.complete && image.naturalWidth > 0)).toBe(true);
  await page.locator('.monaco-editor .view-line').first().waitFor();
  // Menus are mutually exclusive and close on outside click, Escape and activation.
  const menus = page.getByRole('navigation', { name: 'Menus de l’atelier', exact: true });
  await menus.getByRole('button', { name: 'Fichier', exact: true }).click();
  await expect(page.getByRole('menu')).toHaveCount(1);
  await menus.getByRole('button', { name: 'Édition', exact: true }).hover();
  await expect(page.getByRole('menu', { name: 'Édition', exact: true })).toBeVisible();
  await expect(page.getByRole('menu')).toHaveCount(1);
  await page.keyboard.press('Escape'); await expect(page.getByRole('menu')).toHaveCount(0);
  await expect(menus.getByRole('button', { name: 'Édition', exact: true })).toBeFocused();
  await menus.getByRole('button', { name: 'Git', exact: true }).click();
  await page.getByRole('menuitem', { name: /Afficher Git/ }).click();
  await expect(page.getByRole('menu')).toHaveCount(0);
  await expect(page.getByRole('heading', { name: 'Contrôle de version Git', exact: true })).toBeVisible();
  await expect(page.getByRole('complementary', { name: 'Assistant IA', exact: true }).locator('.git-panel,.firmware-panel,.project-files')).toHaveCount(0);
  await menus.getByRole('button', { name: 'Fichier', exact: true }).click();
  await page.getByRole('heading', { name: 'CPCéleste', exact: true }).click();
  await expect(page.getByRole('menu')).toHaveCount(0);
  await menus.getByRole('button', { name: 'Affichage', exact: true }).focus();
  await page.keyboard.press('ArrowDown');
  await expect(page.getByRole('menuitem').first()).toBeFocused();
  await page.keyboard.press('ArrowDown'); await expect(page.getByRole('menuitem').nth(1)).toBeFocused();
  await page.keyboard.press('Escape');
  const left = page.getByRole('complementary', { name: 'Outils du projet', exact: true });
  await page.keyboard.press('Control+b'); await expect(left).toBeHidden();
  await page.keyboard.press('Control+Shift+e'); await expect(left).toBeVisible();
  await page.keyboard.press('Control+Shift+f'); await expect(page.getByRole('region', { name: 'Recherche dans les sources', exact: true })).toBeVisible();
  await page.keyboard.press('Control+Shift+g'); await expect(page.getByRole('heading', { name: 'Contrôle de version Git', exact: true })).toBeVisible();
  await page.keyboard.press('Control+Shift+f'); await expect(page.getByRole('region', { name: 'Recherche dans les sources', exact: true })).toBeVisible();
  await page.keyboard.press('Control+Shift+a'); await expect(page.getByRole('complementary', { name: 'Assistant IA', exact: true })).toBeHidden();
  await page.keyboard.press('Control+Shift+a'); await expect(page.getByRole('complementary', { name: 'Assistant IA', exact: true })).toBeVisible();
  await page.keyboard.press('Control+j'); await expect(page.getByRole('navigation', { name: 'Panneaux de sortie', exact: true })).toBeHidden();
  await page.keyboard.press('Control+j'); await expect(page.getByRole('navigation', { name: 'Panneaux de sortie', exact: true })).toBeVisible();
  assert.equal(await page.locator('.toolbar button:not(:has(svg))').count(), 0, 'Each toolbar action has an accessible SVG icon');
  await page.keyboard.press('Control+Shift+e');
  await verifyPanelLayout(page);
  await page.keyboard.press('Control+Shift+P');
  const palette = page.getByRole('dialog', { name: 'Commandes CPCéleste', exact: true });
  await palette.getByRole('textbox').fill('minimap'); await palette.getByRole('textbox').press('Enter');
  await expect(page.locator('.monaco-editor .minimap')).toBeVisible();
  await page.keyboard.press('Control+p');
  await expect(page.getByRole('dialog', { name: 'Ouvrir rapidement une source', exact: true })).toContainText('MAIN.bas');
  await page.keyboard.press('Escape');
  await page.getByRole('tab', { name: 'MAIN.bas', exact: true }).click({ button: 'right' });
  await expect(page.getByRole('dialog', { name: 'Actions de MAIN.bas', exact: true })).toBeVisible();
  await page.keyboard.press('Escape');
  await page.locator('.monaco-editor .view-line').first().click({ button: 'right' });
  await expect(page.getByText('Renuméroter le BASIC…', { exact: true })).toBeVisible();
  await page.keyboard.press('Escape');
  await page.waitForFunction(() => document.querySelectorAll('.monaco-editor .view-lines span[class*="mtk"]').length > 10);
  const input = page.locator('.monaco-editor textarea');
  await input.focus(); await page.keyboard.press('Control+Home'); await page.keyboard.press('Control+a');
  await page.keyboard.insertText('10 PRI');
  await page.keyboard.press('Control+Space');
  await page.locator('.suggest-widget.visible').waitFor();
  await page.keyboard.press('Enter');
  await page.keyboard.insertText(' "OK"\n20 END\n');
  await page.getByText('Aucun problème détecté dans le sous-ensemble analysé.').waitFor();
  await page.keyboard.press('F1');
  await page.getByRole('button', { name: 'PRINT', exact: true }).click();
  await page.getByRole('heading', { name: 'PRINT', exact: true }).waitFor();
  await input.focus(); await page.keyboard.press('Control+a'); await page.keyboard.insertText('10 MODE\n20 IF A>0\n30 PRINT (1+2');
  await expect(page.locator('.basic-error-glyph')).toHaveCount(3);
  await expect(page.locator('.squiggly-error').first()).toBeVisible();
  await page.getByRole('button', { name: /L2 · Erreur · IF attend/ }).click();
  await expect(page.getByRole('status').filter({ hasText: /L2 · C/ })).toBeVisible();
  await page.keyboard.press('F8');
  await expect(page.getByRole('status').filter({ hasText: /L3 · C/ })).toBeVisible();
  await page.keyboard.press('Escape');
  await input.focus(); await page.keyboard.press('Control+a'); await page.keyboard.insertText('10 PRINT "OK"\n20 END\n');
  await expect(page.locator('.basic-error-glyph')).toHaveCount(0);
  await page.keyboard.press('Control+Home'); await page.keyboard.press('Control+/');
  await expect(page.locator('.view-lines')).toContainText("10 ' PRINT");
  await page.keyboard.press('Control+/'); await expect(page.locator('.view-lines')).toContainText('10 PRINT');
  const diskEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Exporter DSK', exact: true }).click();
  const disk = new Uint8Array(await readFile(await (await diskEvent).path()));
  const files = readDataDisk(disk);
  assert.equal(files[0].name, 'MAIN.BAS');
  assert.equal(new TextDecoder().decode(decodeAsciiRecords(files[0].records)), '10 PRINT "OK"\r\n20 END\r\n\x1a');
  await input.focus(); await page.keyboard.press('Control+a'); await page.keyboard.insertText('10 GOTO 999\n20 END');
  await page.getByRole('button', { name: /La ligne BASIC 999 n’existe/ }).waitFor();
  await page.getByRole('button', { name: 'Exporter DSK', exact: true }).click();
  await page.getByRole('status').filter({ hasText: /999 n’existe/ }).waitFor();
  await input.focus(); await page.keyboard.press('Control+a'); await page.keyboard.insertText('10 GOTO 100\n100 END');
  await page.keyboard.press('Control+Home'); await page.keyboard.press('End'); await page.keyboard.press('F12');
  await page.getByRole('status').filter({ hasText: /L2 · C/ }).waitFor();
  await page.keyboard.press('End'); await page.keyboard.insertText(':REM TARGET');
  const savedEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: /^Enregistrer Ctrl/ }).click();
  const saved = await readFile(await (await savedEvent).path(), 'utf8');
  assert.equal(saved, '10 GOTO 100\n100 END:REM TARGET', 'F12 navigated to BASIC target');
  // Dirty replacement must not silently discard edits.
  await input.focus(); await page.keyboard.press('End'); await page.keyboard.insertText(' X');
  const cancelled = page.waitForEvent('dialog').then(dialog => dialog.dismiss());
  await page.getByRole('button', { name: 'Ouvrir', exact: true }).click();
  await cancelled;
  assert.ok(await page.locator('.tab').textContent().then(text => text.includes('modifié')));
  await page.getByRole('button', { name: 'Renuméroter', exact: true }).click();
  const renumber = page.getByRole('region', { name: 'Renumérotation BASIC' });
  await renumber.getByLabel('Premier nouveau numéro', { exact: true }).fill('1000');
  await renumber.getByRole('button', { name: 'Prévisualiser la renumérotation', exact: true }).click();
  await expectText(renumber, '3 substitutions.');
  await renumber.getByRole('button', { name: 'Appliquer la renumérotation', exact: true }).click();
  await expect(page.locator('.monaco-editor .view-lines')).toContainText('1000 GOTO 1010');
  const renumberDiskEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Exporter DSK', exact: true }).click();
  const renumberDisk = new Uint8Array(await readFile(await (await renumberDiskEvent).path()));
  assert.equal(new TextDecoder().decode(decodeAsciiRecords(readDataDisk(renumberDisk)[0].records)), '1000 GOTO 1010\r\n1010 END:REM TARGET X\r\n\x1a');
  await mkdir('out', { recursive: true }); await page.screenshot({ path: 'out/renumber-alpha.png', fullPage: true });
  await input.focus(); await page.keyboard.press('Control+z');
  await expect(page.locator('.monaco-editor .view-lines')).toContainText('10 GOTO 100');
  await page.keyboard.press('Control+Shift+z');
  await expect(page.locator('.monaco-editor .view-lines')).toContainText('1000 GOTO 1010');
  await page.keyboard.press('Control+z');
  await renumber.getByRole('button', { name: 'Prévisualiser la renumérotation', exact: true }).click();
  await input.focus(); await page.keyboard.press('Control+End'); await page.keyboard.insertText(' Y'); await page.keyboard.press('Control+z');
  await renumber.getByRole('button', { name: 'Appliquer la renumérotation', exact: true }).click();
  await expectText(renumber, 'révision modifié depuis l’aperçu');
  await renumber.getByRole('button', { name: 'Fermer la renumérotation', exact: true }).click();
  await page.keyboard.press('Control+Shift+f');
  const search = page.getByRole('region', { name: 'Recherche dans les sources', exact: true });
  await search.getByLabel('Texte à rechercher', { exact: true }).fill('TARGET');
  await search.getByRole('button', { name: 'Rechercher toutes les sources', exact: true }).click();
  await expect(search).toContainText('1 occurrence(s).');
  await search.getByRole('button', { name: /MAIN.bas · L2:/ }).click();
  await search.getByLabel('Texte de remplacement', { exact: true }).fill('REPLACED');
  await search.getByRole('button', { name: 'Prévisualiser les remplacements', exact: true }).click();
  await search.getByRole('button', { name: 'Appliquer les remplacements sélectionnés', exact: true }).click();
  await expect(page.locator('.monaco-editor .view-lines')).toContainText('REPLACED');
  await input.focus(); await page.keyboard.press('Control+z');
  await expect(page.locator('.monaco-editor .view-lines')).toContainText('TARGET');
  await page.keyboard.press('Control+Shift+z');
  await expect(page.locator('.monaco-editor .view-lines')).toContainText('REPLACED');
  await search.getByRole('button', { name: 'Rechercher toutes les sources', exact: true }).click();
  await input.focus(); await page.keyboard.press('Control+End'); await page.keyboard.insertText(' STALE');
  await expect(search).toContainText('Sources modifiées depuis la recherche');
  await expect(search.getByRole('button', { name: 'Prévisualiser les remplacements', exact: true })).toBeDisabled();
  await mkdir('out', { recursive: true });
  await page.screenshot({ path: 'out/editor-alpha.png', fullPage: true });
  await page.getByRole('button', { name: 'Exécuter F5', exact: true }).click();
  const editorBounds = await page.locator('.editor-host').boundingBox();
  assert.ok(editorBounds.height >= 140 && editorBounds.y + editorBounds.height < 940, 'Emulator leaves editor visible');
  await page.getByRole('button', { name: 'Arrêter et fermer le CPC', exact: true }).click();
  await page.setViewportSize({ width: 1024, height: 768 });
  assert.ok((await page.locator('.editor-host').boundingBox()).height >= 140, 'Code remains visible in a smaller window');
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'No page-wide horizontal overflow');
  await page.setViewportSize({ width: 1440, height: 960 });
  await mkdir('out', { recursive: true }); await page.screenshot({ path: 'out/workbench-alpha.png' });
  // Preferences apply to the existing buffer and persist across windows of the same profile.
  await page.keyboard.press('Control+,');
  let settings = page.getByRole('dialog', { name: 'Paramètres de CPCéleste', exact: true });
  await settings.getByLabel('Thème', { exact: true }).selectOption('light');
  await settings.getByLabel('Taille du code (px)', { exact: true }).fill('19');
  await settings.getByLabel('Police du code', { exact: true }).fill('Courier New, monospace');
  await settings.getByLabel('Taille d’indentation', { exact: true }).fill('4');
  await settings.getByLabel('Largeur des outils (px)', { exact: true }).fill('280');
  await settings.getByLabel('Largeur de l’assistant (px)', { exact: true }).fill('330');
  await settings.getByRole('button', { name: 'Appliquer les paramètres', exact: true }).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
  await expect.poll(async () => Math.round((await left.boundingBox()).width)).toBe(280);
  await expect(page.locator('.view-lines')).toContainText('REPLACED');
  await expect.poll(() => page.locator('.view-lines').evaluate(element => getComputedStyle(element).fontSize)).toBe('19px');
  const settingsPage = await page.context().newPage();
  settingsPage.on('pageerror', error => errors.push(error.message));
  await settingsPage.addInitScript(() => { window.open = url => { window.lastFeedbackURL = String(url); return null; }; });
  await settingsPage.goto('http://127.0.0.1:5173');
  await expect(settingsPage.locator('html')).toHaveAttribute('data-theme', 'light');
  await settingsPage.keyboard.press('Control+,');
  settings = settingsPage.getByRole('dialog', { name: 'Paramètres de CPCéleste', exact: true });
  await expect(settings.getByLabel('Police du code', { exact: true })).toHaveValue('Courier New, monospace');
  await expect(settings.getByLabel('Taille du code (px)', { exact: true })).toHaveValue('19');
  await expect(settings.getByLabel('Taille d’indentation', { exact: true })).toHaveValue('4');
  await settings.getByLabel('Thème', { exact: true }).selectOption('system');
  await settings.getByRole('button', { name: 'Appliquer les paramètres', exact: true }).click();
  await settingsPage.emulateMedia({ colorScheme: 'dark' }); await expect(settingsPage.locator('html')).toHaveAttribute('data-theme', 'dark');
  await settingsPage.emulateMedia({ colorScheme: 'light' }); await expect(settingsPage.locator('html')).toHaveAttribute('data-theme', 'light');
  await settingsPage.screenshot({ path: 'out/workbench-light.png' });
  await settingsPage.keyboard.press('Control+,');
  settings = settingsPage.getByRole('dialog', { name: 'Paramètres de CPCéleste', exact: true });
  await settings.getByRole('button', { name: 'Valeurs par défaut', exact: true }).click();
  await settings.getByRole('button', { name: 'Appliquer les paramètres', exact: true }).click();
  await expect(settingsPage.locator('html')).toHaveAttribute('data-theme', 'dark');
  await settingsPage.getByRole('navigation', { name: 'Menus de l’atelier', exact: true }).getByRole('button', { name: 'Aide', exact: true }).click();
  await settingsPage.getByRole('menuitem', { name: 'Proposer une amélioration ou signaler un problème', exact: true }).click();
  const feedback = settingsPage.getByRole('dialog', { name: 'Faire évoluer CPCéleste', exact: true });
  await expect(feedback.getByRole('button', { name: 'Ouvrir le ticket GitHub', exact: true })).toBeDisabled();
  await feedback.getByLabel('Titre de la demande', { exact: true }).fill('Comparer deux sources');
  await feedback.getByLabel('Mon utilisation de l’IDE', { exact: true }).fill('Je programme des jeux CPC.');
  await feedback.getByLabel('Besoin et difficulté actuelle', { exact: true }).fill('Afficher deux fichiers ensemble.');
  await feedback.getByRole('button', { name: 'Ouvrir le ticket GitHub', exact: true }).click();
  await expect(feedback).toContainText('Ticket prérempli ouvert');
  const ticketURL = new URL(await settingsPage.evaluate(() => window.lastFeedbackURL));
  assert.equal(ticketURL.origin + ticketURL.pathname, 'https://github.com/AstrowareConception/Micro-IDE-Amstrad/issues/new');
  assert.equal(ticketURL.searchParams.get('title'), '[Amélioration] Comparer deux sources');
  assert.ok(ticketURL.searchParams.get('body').includes('Je programme des jeux CPC.'));
  await settingsPage.close();
  // UI model catalogue recipe uses a deterministic IPC fixture, never a paid API call.
  const modelsPage = await browser.newPage({ viewport: { width: 1440, height: 960 } });
  modelsPage.on('pageerror', error => errors.push(error.message));
  await modelsPage.addInitScript(() => {
    let calls = 0, chosen = '';
    const realNow = Date.now.bind(Date);
    window.advanceCatalogueTime = offset => { Date.now = () => realNow() + offset; };
    const realSetInterval = window.setInterval.bind(window);
    // Accelerate only the catalogue cadence; keep animation/performance clocks native.
    window.setInterval = (handler, delay, ...args) => realSetInterval(handler, delay === 60000 ? 1000 : delay, ...args);
    window.autoSaveCalls = [];
    window.desktop = { project: { saveAll: async (sessionId, sources) => { window.autoSaveCalls.push({ sessionId, sources }); return { name: 'Recette sources', savedIds: sources.map(source => source.id), changedCount: sources.length }; }, open: async () => ({ sessionId: 'ui-tabs', manifest: { name: 'Recette sources', sources: [{ id: 'main', path: 'src/main.bas', cpcName: 'MAIN.BAS' }, { id: 'util', path: 'src/util.bas', cpcName: 'UTIL.BAS' }], entryPoint: 'main', documents: [] }, files: [{ id: 'main', path: 'src/main.bas', source: '10 REM MAIN\n20 END\n' }, { id: 'util', path: 'src/util.bas', source: '10 REM UTIL\n20 RETURN\n' }] }) }, setDirty() {}, open: async () => null, save: async () => null, exportDisk: async () => null, agent: {
      models: async key => {
        calls++;
        if (calls === 3) return { error: 'Connexion indisponible (recette)' };
        if (key !== undefined) { if (key !== 'sk-ui-fixture-not-real') return { error: 'Clé refusée' }; chosen = ''; }
        return { models: [{ id: 'gpt-99-ui', created: 100, owner: 'openai' }, ...(calls > 1 ? [{ id: 'gpt-100-ui-new', created: 200, owner: 'openai' }] : []), ...(calls >= 4 ? [{ id: 'gpt-101-ui-timer', created: 300, owner: 'openai' }] : []), ...(calls >= 5 ? [{ id: 'gpt-102-ui-focus', created: 400, owner: 'openai' }] : [])], fetchedAt: new Date(Date.now()).toISOString(), model: chosen };
      },
      selectModel: async model => { chosen = model; return { model }; },
      configure: async key => { if (key !== '') throw new Error('UI must use official listing'); chosen = ''; return { configured: false, model: '' }; },
    } };
  });
  await modelsPage.goto('http://127.0.0.1:5173');
  const modelPicker = modelsPage.getByRole('combobox', { name: 'Modèle OpenAI', exact: true });
  await expect(modelPicker).toBeDisabled();
  await expect(modelsPage.getByRole('textbox', { name: 'Modèle OpenAI', exact: true })).toHaveCount(0);
  await modelsPage.getByLabel('Clé API OpenAI', { exact: true }).fill('sk-ui-fixture-not-real');
  await modelsPage.getByRole('button', { name: 'Configurer la clé', exact: true }).click();
  await expect(modelPicker).toBeEnabled(); await expect(modelPicker).toHaveValue('');
  await expect(modelsPage.getByLabel('Clé API OpenAI', { exact: true })).toHaveValue('');
  await modelPicker.selectOption('gpt-99-ui'); await expect(modelPicker).toHaveValue('gpt-99-ui');
  await modelsPage.getByRole('button', { name: 'Détacher l’agent IA', exact: true }).click();
  await expect(modelPicker).toHaveValue('gpt-99-ui');
  await modelsPage.getByRole('button', { name: 'Réancrer l’agent IA', exact: true }).click();
  await expect(modelPicker).toHaveValue('gpt-99-ui');
  await modelsPage.getByRole('button', { name: 'Actualiser les modèles', exact: true }).click();
  await expect(modelPicker).toContainText('gpt-100-ui-new'); await expect(modelPicker).toHaveValue('gpt-99-ui');
  await modelPicker.selectOption('gpt-100-ui-new'); await expect(modelPicker).toHaveValue('gpt-100-ui-new');
  await modelsPage.getByRole('button', { name: 'Actualiser les modèles', exact: true }).click();
  await expect(modelsPage.locator('.agent-notice')).toContainText('Dernière liste conservée');
  await expect(modelPicker).toHaveValue('gpt-100-ui-new');
  await modelsPage.evaluate(() => window.advanceCatalogueTime(16 * 60 * 1000));
  await expect(modelPicker).toContainText('gpt-101-ui-timer');
  await expect(modelPicker).toHaveValue('gpt-100-ui-new');
  await modelsPage.evaluate(() => window.advanceCatalogueTime(32 * 60 * 1000));
  await modelsPage.evaluate(() => window.dispatchEvent(new Event('focus')));
  await expect(modelPicker).toContainText('gpt-102-ui-focus');
  await expect(modelPicker).toHaveValue('gpt-100-ui-new');
  await modelsPage.screenshot({ path: 'out/models-alpha.png' });
  await modelsPage.getByRole('button', { name: 'Oublier la clé', exact: true }).click();
  await expect(modelPicker).toBeDisabled(); await expect(modelPicker).toHaveValue('');
  await modelsPage.getByRole('button', { name: 'Ouvrir projet', exact: true }).click();
  await modelsPage.bringToFront();
  const modelInput = modelsPage.locator('.listing .monaco-editor textarea');
  await expect(modelsPage.locator('.view-lines')).toContainText('10 REM MAIN');
  await modelInput.focus(); await modelsPage.keyboard.press('Control+End'); await modelsPage.keyboard.insertText('30 REM MAIN DRAFT');
  await modelsPage.getByRole('tab', { name: /src\/util.bas/ }).click();
  await expect(modelsPage.locator('.view-lines')).toContainText('10 REM UTIL');
  await modelInput.focus(); await modelsPage.keyboard.press('Control+End'); await modelsPage.keyboard.insertText('30 REM UTIL DRAFT');
  await modelsPage.getByRole('tab', { name: /src\/util.bas/ }).click({ button: 'middle' });
  await expect(modelsPage.getByRole('tab', { name: /src\/util.bas/ })).toHaveCount(0);
  await modelsPage.getByRole('navigation', { name: 'Explorateur de sources', exact: true }).getByRole('button', { name: /^src\/util.bas/ }).click();
  await expect(modelsPage.locator('.view-lines')).toContainText('UTIL DRAFT');
  await modelsPage.keyboard.press('Control+w');
  await modelsPage.keyboard.press('Control+p');
  await modelsPage.getByRole('dialog', { name: 'Ouvrir rapidement une source', exact: true }).getByRole('textbox').fill('util.bas');
  await modelsPage.keyboard.press('Enter');
  await expect(modelsPage.locator('.view-lines')).toContainText('UTIL DRAFT');
  await expect(modelsPage.locator('.view-lines .view-line')).toHaveCount(3);
  await modelsPage.getByRole('tab', { name: /src\/main.bas/ }).click();
  await expect(modelsPage.locator('.view-lines')).toContainText('MAIN DRAFT');
  await expect(modelsPage.locator('.view-lines')).not.toContainText('TARGET');
  await modelInput.focus(); await modelsPage.keyboard.press('Control+z');
  await expect(modelsPage.locator('.view-lines')).not.toContainText('MAIN DRAFT');
  await modelsPage.keyboard.press('Control+Shift+z'); await expect(modelsPage.locator('.view-lines')).toContainText('MAIN DRAFT');
  await expect.poll(() => modelsPage.evaluate(() => window.autoSaveCalls.length)).toBe(0);
  await modelsPage.keyboard.press('Control+,');
  const autoSettings = modelsPage.getByRole('dialog', { name: 'Paramètres de CPCéleste', exact: true });
  await autoSettings.getByLabel('Enregistrement automatique des sources du projet', { exact: true }).check();
  await autoSettings.getByLabel('Délai d’enregistrement automatique (ms)', { exact: true }).fill('1000');
  await autoSettings.getByRole('button', { name: 'Appliquer les paramètres', exact: true }).click();
  await expect.poll(() => modelsPage.evaluate(() => window.autoSaveCalls.length)).toBe(1);
  const automaticBatch = await modelsPage.evaluate(() => window.autoSaveCalls[0]);
  assert.deepEqual(automaticBatch.sources.map(source => source.id), ['main', 'util']);
  assert.ok(automaticBatch.sources.every(source => source.source.includes('DRAFT')));
  await expect(modelsPage.getByRole('tab', { name: /modifié/ })).toHaveCount(0);
  await modelsPage.close();
  assert.deepEqual(errors, [], 'No browser errors');
  console.log('Editor browser smoke: completion, coloration, help, diagnostics, F12, downloads, dirty protection plus renumber preview/apply/DSK/undo/redo/stale revision passed.');
} catch (error) {
  await mkdir('out', { recursive: true });
  await page?.screenshot({ path: 'out/editor-failure.png', fullPage: true, timeout: 5000 }).catch(() => undefined);
  console.error('Browser errors:', errors);
  console.error(await page?.locator('.view-lines').textContent());
  throw error;
} finally { await browser?.close(); server.kill(); }

async function expectText(locator, text) {
  await locator.getByText(text, { exact: false }).waitFor();
}
