const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('desktop', Object.freeze({
  open: () => ipcRenderer.invoke('listing:open'),
  save: (source, saveAs = false) => ipcRenderer.invoke('listing:save', { source, saveAs }),
  exportDisk: source => ipcRenderer.invoke('listing:export', { source }),
  feedback: Object.freeze({ open: input => ipcRenderer.invoke('feedback:open', input) }),
  setDirty: dirty => ipcRenderer.send('listing:dirty', dirty),
  history: Object.freeze({
    list: sessionId => ipcRenderer.invoke('history:list', { sessionId }),
    version: (sessionId, snapshotId, id, revision) => ipcRenderer.invoke('history:version', { sessionId, snapshotId, id, revision }),
  }),
  external: Object.freeze({
    status: sessionId => ipcRenderer.invoke('external:status', { sessionId }),
    read: (sessionId, id, revision) => ipcRenderer.invoke('external:read', { sessionId, id, revision }),
    accept: (sessionId, id, revision, baseRevision) => ipcRenderer.invoke('external:accept', { sessionId, id, revision, baseRevision }),
  }),
  drafts: Object.freeze({
    status: sessionId => ipcRenderer.invoke('drafts:status', { sessionId }),
    capture: (sessionId, sources, revision) => ipcRenderer.invoke('drafts:capture', { sessionId, sources, revision }),
    read: (sessionId, revision) => ipcRenderer.invoke('drafts:read', { sessionId, revision }),
    forget: (sessionId, revision) => ipcRenderer.invoke('drafts:forget', { sessionId, revision }),
  }),
  terminal: Object.freeze({
    run: (sessionId, command) => ipcRenderer.invoke('terminal:run', { sessionId, command }),
    status: (sessionId, id) => ipcRenderer.invoke('terminal:status', { sessionId, id }),
    stop: (sessionId, id) => ipcRenderer.invoke('terminal:stop', { sessionId, id }),
  }),
  git: Object.freeze({
    identity: sessionId => ipcRenderer.invoke('git:identity', { sessionId }),
    rememberIdentity: (sessionId, revision, identity) => ipcRenderer.invoke('git:remember-identity', { sessionId, revision, identity }),
    forgetIdentity: (sessionId, revision) => ipcRenderer.invoke('git:forget-identity', { sessionId, revision }),
    prepareCommit: (sessionId, input) => ipcRenderer.invoke('git:prepare-commit', { sessionId, input }),
    commit: (sessionId, planId) => ipcRenderer.invoke('git:commit', { sessionId, planId }),
    status: sessionId => ipcRenderer.invoke('git:status', { sessionId }),
    diff: (sessionId, changeId, side) => ipcRenderer.invoke('git:diff', { sessionId, changeId, side }),
    history: (sessionId, cursor) => ipcRenderer.invoke('git:history', { sessionId, cursor }),
    prepareInit: sessionId => ipcRenderer.invoke('git:prepare-init', { sessionId }),
    init: (sessionId, planId) => ipcRenderer.invoke('git:init', { sessionId, planId }),
    changeIndex: (sessionId, snapshotId, changeId, action) => ipcRenderer.invoke('git:index', { sessionId, snapshotId, changeId, action }),
  }),
  gitOperations: Object.freeze({
    cancel: () => ipcRenderer.invoke('git:cancel'),
    overview: sessionId => ipcRenderer.invoke('git:overview', { sessionId }),
    prepare: (sessionId, revision, request) => ipcRenderer.invoke('git:prepare-operation', { sessionId, revision, request }),
    apply: (sessionId, planId) => ipcRenderer.invoke('git:apply-operation', { sessionId, planId }),
    clone: (url, name) => ipcRenderer.invoke('git:clone', { url, name }),
    suggestMessage: (sessionId, identity) => ipcRenderer.invoke('git:suggest-message', { sessionId, identity }),
  }),
  github: Object.freeze({
    account: () => ipcRenderer.invoke('github:account'),
    connect: token => ipcRenderer.invoke('github:connect', token),
    connectCLI: () => ipcRenderer.invoke('github:connect-cli'),
    disconnect: () => ipcRenderer.invoke('github:disconnect'),
    tokenPage: () => ipcRenderer.invoke('github:token-page'),
    repositories: page => ipcRenderer.invoke('github:repositories', page),
    createRepository: (name, isPrivate) => ipcRenderer.invoke('github:create-repository', { name, isPrivate }),
    pullRequests: (sessionId, remote) => ipcRenderer.invoke('github:pull-requests', { sessionId, remote }),
    createPullRequest: (sessionId, remote, base, title, body, draft) => ipcRenderer.invoke('github:create-pull-request', { sessionId, remote, base, title, body, draft }),
    open: url => ipcRenderer.invoke('github:open', url),
  }),
  emulator: Object.freeze({ prepare: request => ipcRenderer.invoke('emulator:prepare', request), exportDisk: (disk, sessionId) => ipcRenderer.invoke('emulator:export', { disk, sessionId }) }),
  firmware: Object.freeze({
    status: () => ipcRenderer.invoke('firmware:status'),
    importRom: role => ipcRenderer.invoke('firmware:import', role),
    clear: () => ipcRenderer.invoke('firmware:clear'),
  }),
  agent: Object.freeze({
    configure: (key, model) => ipcRenderer.invoke('agent:configure', { key, model }),
    models: key => ipcRenderer.invoke('agent:models', key === undefined ? undefined : { key }),
    selectModel: model => ipcRenderer.invoke('agent:select-model', model),
    pricing: model => ipcRenderer.invoke('agent:pricing', model),
    start: (sessionId, objective, buffers, includeDocuments = false, budget) => ipcRenderer.invoke('agent:start', { sessionId, objective, buffers, includeDocuments, budget }),
    resume: (taskId, buffers, sessionId) => ipcRenderer.invoke('agent:resume', { taskId, buffers, sessionId }),
    status: taskId => ipcRenderer.invoke('agent:status', taskId),
    cancel: taskId => ipcRenderer.invoke('agent:cancel', taskId),
    steer: (taskId, instruction) => ipcRenderer.invoke('agent:steer', { taskId, instruction }),
    restore: (taskId, buffers, sessionId) => ipcRenderer.invoke('agent:restore', { taskId, buffers, sessionId }),
  }),
  recentProjects: Object.freeze({
    list: () => ipcRenderer.invoke('recent-projects:list'),
    open: id => ipcRenderer.invoke('recent-projects:open', id),
    remove: id => ipcRenderer.invoke('recent-projects:remove', id),
    clear: () => ipcRenderer.invoke('recent-projects:clear'),
  }),
  explorer: Object.freeze({
    list: (sessionId, directory, showHidden) => ipcRenderer.invoke('explorer:list', { sessionId, directory, showHidden }),
    preview: (sessionId, path, revision) => ipcRenderer.invoke('explorer:preview', { sessionId, path, revision }),
  }),
  sourceOperations: Object.freeze({
    prepare: (sessionId, request) => ipcRenderer.invoke('sources:prepare', { sessionId, request }),
    apply: (sessionId, planId, source) => ipcRenderer.invoke('sources:apply', { sessionId, planId, source }),
    last: sessionId => ipcRenderer.invoke('sources:last', { sessionId }),
    restore: (sessionId, revision) => ipcRenderer.invoke('sources:restore', { sessionId, revision }),
    draft: sessionId => ipcRenderer.invoke('sources:draft', { sessionId }),
  }),
  basicTestSuites: Object.freeze({
    load: sessionId => ipcRenderer.invoke('basic-tests:load', { sessionId }),
    save: (sessionId, revision, suites) => ipcRenderer.invoke('basic-tests:save', { sessionId, revision, suites }),
    history: sessionId => ipcRenderer.invoke('basic-tests:history', { sessionId }),
    record: (sessionId, report) => ipcRenderer.invoke('basic-tests:record', { sessionId, report }),
  }),
  project: Object.freeze({
    open: () => ipcRenderer.invoke('project:open'),
    create: name => ipcRenderer.invoke('project:create', name),
    save: (sessionId, id, source) => ipcRenderer.invoke('project:save', { sessionId, id, source }),
    saveAll: (sessionId, sources) => ipcRenderer.invoke('project:save-all', { sessionId, sources }),
    add: (sessionId, name) => ipcRenderer.invoke('project:add', { sessionId, name }),
    setEntry: (sessionId, id) => ipcRenderer.invoke('project:entry', { sessionId, id }),
    exportDisk: (sessionId, sources) => ipcRenderer.invoke('project:export', { sessionId, sources }),
    importDocument: (sessionId, kind = 'text') => ipcRenderer.invoke('documents:import', { sessionId, kind }),
    readDocument: (sessionId, id) => ipcRenderer.invoke('documents:read', { sessionId, id }),
  }),
}));
